{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/TEWODROS\\SQL2022;ContosoRetailDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "TEWODROS\\SQL2022",
            "database": "ContosoRetailDW"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "tewodros\\sql2022;ContosoRetailDW",
          "Username": "ReportUser",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "Sales",
        "columns": [
          {
            "name": "SalesKey",
            "dataType": "int64",
            "sourceColumn": "SalesKey"
          },
          {
            "name": "DateKey",
            "dataType": "dateTime",
            "sourceColumn": "DateKey"
          },
          {
            "name": "channelKey",
            "dataType": "int64",
            "sourceColumn": "channelKey"
          },
          {
            "name": "StoreKey",
            "dataType": "int64",
            "sourceColumn": "StoreKey"
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "sourceColumn": "ProductKey"
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "sourceColumn": "PromotionKey"
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "sourceColumn": "CurrencyKey"
          },
          {
            "name": "UnitCost",
            "dataType": "decimal",
            "sourceColumn": "UnitCost"
          },
          {
            "name": "UnitPrice",
            "dataType": "decimal",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "SalesQuantity",
            "dataType": "int64",
            "sourceColumn": "SalesQuantity"
          },
          {
            "name": "ReturnQuantity",
            "dataType": "int64",
            "sourceColumn": "ReturnQuantity"
          },
          {
            "name": "ReturnAmount",
            "dataType": "decimal",
            "sourceColumn": "ReturnAmount"
          },
          {
            "name": "DiscountQuantity",
            "dataType": "int64",
            "sourceColumn": "DiscountQuantity"
          },
          {
            "name": "DiscountAmount",
            "dataType": "decimal",
            "sourceColumn": "DiscountAmount"
          },
          {
            "name": "TotalCost",
            "dataType": "decimal",
            "sourceColumn": "TotalCost"
          },
          {
            "name": "SalesAmount",
            "dataType": "decimal",
            "sourceColumn": "SalesAmount"
          },
          {
            "name": "ETLLoadID",
            "dataType": "int64",
            "sourceColumn": "ETLLoadID"
          },
          {
            "name": "LoadDate",
            "dataType": "dateTime",
            "sourceColumn": "LoadDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/TEWODROS\\SQL2022;ContosoRetailDW\",",
                "    dbo_FactSales = Source{[Schema=\"dbo\",Item=\"FactSales\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_FactSales,{\"DimChannel\", \"DimCurrency\", \"DimDate\", \"DimProduct\", \"DimPromotion\", \"DimStore\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "TotalSalesAmt",
            "expression": "SUM(Sales[SalesAmount])"
          },
          {
            "name": "TotalCostAmt",
            "expression": "SUM(Sales[TotalCost])"
          }
        ]
      },
      {
        "name": "Date",
        "columns": [
          {
            "name": "Datekey",
            "dataType": "dateTime",
            "sourceColumn": "Datekey"
          },
          {
            "name": "FullDateLabel",
            "dataType": "string",
            "sourceColumn": "FullDateLabel"
          },
          {
            "name": "DateDescription",
            "dataType": "string",
            "sourceColumn": "DateDescription"
          },
          {
            "name": "CalendarYear",
            "dataType": "int64",
            "sourceColumn": "CalendarYear"
          },
          {
            "name": "CalendarYearLabel",
            "dataType": "string",
            "sourceColumn": "CalendarYearLabel"
          },
          {
            "name": "CalendarHalfYear",
            "dataType": "int64",
            "sourceColumn": "CalendarHalfYear"
          },
          {
            "name": "CalendarHalfYearLabel",
            "dataType": "string",
            "sourceColumn": "CalendarHalfYearLabel"
          },
          {
            "name": "CalendarQuarter",
            "dataType": "int64",
            "sourceColumn": "CalendarQuarter"
          },
          {
            "name": "CalendarQuarterLabel",
            "dataType": "string",
            "sourceColumn": "CalendarQuarterLabel"
          },
          {
            "name": "CalendarMonth",
            "dataType": "int64",
            "sourceColumn": "CalendarMonth"
          },
          {
            "name": "CalendarMonthLabel",
            "dataType": "string",
            "sourceColumn": "CalendarMonthLabel"
          },
          {
            "name": "CalendarWeek",
            "dataType": "int64",
            "sourceColumn": "CalendarWeek"
          },
          {
            "name": "CalendarWeekLabel",
            "dataType": "string",
            "sourceColumn": "CalendarWeekLabel"
          },
          {
            "name": "CalendarDayOfWeek",
            "dataType": "int64",
            "sourceColumn": "CalendarDayOfWeek"
          },
          {
            "name": "CalendarDayOfWeekLabel",
            "dataType": "string",
            "sourceColumn": "CalendarDayOfWeekLabel"
          },
          {
            "name": "FiscalYear",
            "dataType": "int64",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "FiscalYearLabel",
            "dataType": "string",
            "sourceColumn": "FiscalYearLabel"
          },
          {
            "name": "FiscalHalfYear",
            "dataType": "int64",
            "sourceColumn": "FiscalHalfYear"
          },
          {
            "name": "FiscalHalfYearLabel",
            "dataType": "string",
            "sourceColumn": "FiscalHalfYearLabel"
          },
          {
            "name": "FiscalQuarter",
            "dataType": "int64",
            "sourceColumn": "FiscalQuarter"
          },
          {
            "name": "FiscalQuarterLabel",
            "dataType": "string",
            "sourceColumn": "FiscalQuarterLabel"
          },
          {
            "name": "FiscalMonth",
            "dataType": "int64",
            "sourceColumn": "FiscalMonth"
          },
          {
            "name": "FiscalMonthLabel",
            "dataType": "string",
            "sourceColumn": "FiscalMonthLabel"
          },
          {
            "name": "IsWorkDay",
            "dataType": "string",
            "sourceColumn": "IsWorkDay"
          },
          {
            "name": "IsHoliday",
            "dataType": "int64",
            "sourceColumn": "IsHoliday"
          },
          {
            "name": "HolidayName",
            "dataType": "string",
            "sourceColumn": "HolidayName"
          },
          {
            "name": "EuropeSeason",
            "dataType": "string",
            "sourceColumn": "EuropeSeason"
          },
          {
            "name": "NorthAmericaSeason",
            "dataType": "string",
            "sourceColumn": "NorthAmericaSeason"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/TEWODROS\\SQL2022;ContosoRetailDW\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimDate,{\"FactExchangeRate\", \"FactITMachine\", \"FactITSLA\", \"FactInventory\", \"FactOnlineSales\", \"FactSales\", \"FactSalesQuota\", \"FactStrategyPlan\", \"AsiaSeason\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}